config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end
  end
  resources :events, :only => [:index, :show, :destroy]
  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"
  post "/users/:user_id/webhooks/:agent_id/:secret" => "webhooks#create"

#  match "/delayed_job" => DelayedJobWeb, :anchor => false
  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

app/models/agent.rb
require 'serialize_and_symbolize'
require 'assignable_types'
require 'markdown_class_attributes'
require 'utils'

class Agent < ActiveRecord::Base
  include SerializeAndSymbolize
  include AssignableTypes
  include MarkdownClassAttributes

  serialize_and_symbolize :options, :memory
  markdown_class_attributes :description, :event_description

  load_types_in "Agents"

  SCHEDULES = %w[every_2m every_5m every_10m every_30m every_1h every_2h every_5h every_12h every_1d every_2d every_7d
                 midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm]

  attr_accessible :options, :memory, :name, :type, :schedule, :source_ids

  validates_presence_of :name, :user
  validate :sources_are_owned
  validate :validate_schedule

  after_initialize :set_default_schedule
  before_validation :set_default_schedule
  before_validation :unschedule_if_cannot_schedule
  before_save :unschedule_if_cannot_schedule

  belongs_to :user, :inverse_of => :agents
  has_many :events, :dependent => :delete_all, :inverse_of => :agent, :order => "events.id desc"
  has_many :received_events, :through => :sources, :class_name => "Event", :source => :events, :order => "events.id desc"
  has_many :links_as_source, :dependent => :delete_all, :foreign_key => "source_id", :class_name => "Link", :inverse_of => :source
  has_many :links_as_receiver, :dependent => :delete_all, :foreign_key => "receiver_id", :class_name => "Link", :inverse_of => :receiver
  has_many :sources, :through => :links_as_receiver, :class_name => "Agent", :inverse_of => :receivers
  has_many :receivers, :through => :links_as_source, :class_name => "Agent", :inverse_of => :sources

  scope :of_type, lambda { |type|
    type = case type
             when String, Symbol, Class
               type.to_s
             when Agent
               type.class.to_s
             else
               type.to_s
           end
    where(:type => type)
  }

  def check
    # Implement me in your subclass of Agent.
  end

  def default_options
    # Implement me in your subclass of Agent.
    {}
  end

  def receive(events)
    # Implement me in your subclass of Agent.
  end

  def receive_webhook(params)
    # Implement me in your subclass of Agent.
    ["not implemented", 404]
  end

  # Implement me in your subclass to decide if your Agent is working.
  def working?
    raise "Implement me in your subclass"
  end

  def event_created_within(seconds)
    last_event = events.first
    last_event && last_event.created_at > seconds.ago && last_event
  end

  def sources_are_owned
    errors.add(:sources, "must be owned by you") unless sources.all? {|s| s.user == user }
  end

  def create_event(attrs)
    events.create!({ :user => user }.merge(attrs))
  end

  def validate_schedule
    unless cannot_be_scheduled?
      errors.add(:schedule, "is not a valid schedule") unless SCHEDULES.include?(schedule.to_s)
    end
  end

  def make_message(payload, message = options[:message])
    message.gsub(/<([^>]+)>/) { Utils.value_at(payload, $1) || "??" }
  end

  def trigger_webhook(params)
    receive_webhook(params).tap do
      self.last_webhook_at = Time.now
      save!
    end
  end

  def set_default_schedule
    self.schedule = default_schedule unless schedule.present? || cannot_be_scheduled?
  end

  def unschedule_if_cannot_schedule
    self.schedule = nil if cannot_be_scheduled?
  end

  def last_event_at
    @memoized_last_event_at ||= events.select(:created_at).first.try(:created_at)
  end

  def default_schedule
    self.class.default_schedule
  end

  def cannot_be_scheduled?
    self.class.cannot_be_scheduled?
  end

  def can_be_scheduled?
    !cannot_be_scheduled?
  end

  def cannot_receive_events?
    self.class.cannot_receive_events?
  end

  def can_receive_events?
    !cannot_receive_events?
  end

  # Class Methods
  class << self
    def cannot_be_scheduled!
      @cannot_be_scheduled = true
    end

    def cannot_be_scheduled?
      !!@cannot_be_scheduled
    end

    def default_schedule(schedule = nil)
      @default_schedule = schedule unless schedule.nil?
      @default_schedule
    end

    def cannot_receive_events!
      @cannot_receive_events = true
    end

    def cannot_receive_events?
      !!@cannot_receive_events
    end

    def receive!
      sql = Agent.
              select("agents.id AS receiver_agent_id, sources.id AS source_agent_id, events.id AS event_id").
              joins("JOIN links ON (links.receiver_id = agents.id)").
              joins("JOIN agents AS sources ON (links.source_id = sources.id)").
              joins("JOIN events ON (events.agent_id = sources.id)").
              where("agents.last_checked_event_id IS NULL OR events.id > agents.last_checked_event_id").to_sql

      agents_to_events = {}
      Agent.connection.select_rows(sql).each do |receiver_agent_id, source_agent_id, event_id|
        agents_to_events[receiver_agent_id] ||= []
        agents_to_events[receiver_agent_id] << event_id
      end

      event_ids = agents_to_events.values.flatten.uniq.compact

      Agent.where(:id => agents_to_events.keys).each do |agent|
        agent.update_attribute :last_checked_event_id, event_ids.max
        Agent.async_receive(agent.id, agents_to_events[agent.id].uniq)
      end

      {
          :agent_count => agents_to_events.keys.length,
          :event_count => event_ids.length
      }
    end

    # Given an Agent id and an array of Event ids, load the Agent, call #receive on it with the Event objects, and then
    # save it with an updated _last_receive_at_ timestamp.
    #
    # This method is tagged with _handle_asynchronously_ and will be delayed and run with delayed_job.  It accepts Agent
    # and Event ids instead of a literal ActiveRecord models because it is preferable to serialize delayed_jobs with ids.
    def async_receive(agent_id, event_ids)
      agent = Agent.find(agent_id)
      agent.receive(Event.where(:id => event_ids))
      agent.last_receive_at = Time.now
      agent.save!
    end
    handle_asynchronously :async_receive

    def run_schedule(schedule)
      types = where(:schedule => schedule).group(:type).pluck(:type)
      types.each do |type|
        type.constantize.bulk_check(schedule)
      end
    end

    # You can override this to define a custom bulk_check for your type of Agent.
    def bulk_check(schedule)
      raise "Call #bulk_check on the appropriate subclass of Agent" if self == Agent
      where(:schedule => schedule).pluck("agents.id").each do |agent_id|
        async_check(agent_id)
      end
    end

    # Given an Agent id, load the Agent, call #check on it, and then save it with an updated _last_check_at_ timestamp.
    #
    # This method is tagged with _handle_asynchronously_ and will be delayed and run with delayed_job.  It accepts an Agent
    # id instead of a literal Agent because it is preferable to serialize delayed_jobs with ids.
    def async_check(agent_id)
      agent = Agent.find(agent_id)
      agent.check
      agent.last_check_at = Time.now
      agent.save!
    end
    handle_asynchronously :async_check
  end
end

app/models/agents/adioso_agent.rb
module Agents
  class AdiosoAgent < Agent

    cannot_receive_events!

  	default_schedule "every_1d"

    description <<-MD
  		The Adioso Agent will tell you the minimum airline prices between a pair of cities, and within a certain period of time.
      The currency is USD. Please make sure that the difference between `start_date` and `end_date` is less than 150 days. You will need to contact [Adioso](http://adioso.com/)
  		for a `username` and `password`.
    MD

    event_description <<-MD
      If flights are present then events look like:

  		    { "cost" : 75.23,
            "date" : "June 25, 2013",
  			    "route" : "New York to Chicago" }

      otherwise
    
          { "nonetodest" : "No flights found to the specified destination" }
    MD

    def default_options
      {
        :start_date => Date.today.httpdate[0..15],
        :end_date   => Date.today.plus_with_duration(100).httpdate[0..15],
        :from       => "New York",
        :to         => "Chicago",
        :username   => "xx",
        :password   => "xx",
				:expected_update_period_in_days => "1"
      }
    end

    def working?
      (event = event_created_within(options[:expected_update_period_in_days].to_i.days)) && event.payload.present?
    end

    def validate_options
			unless %w[start_date end_date from to username password expected_update_period_in_days].all? { |field| options[field.to_sym].present? }
				errors.add(:base, "All fields are required")
			end
		end

    def date_to_unix_epoch(date)
      date.to_time.to_i
    end

    def check
      auth_options = {:basic_auth => {:username =>options[:username], :password=>options[:password]}}
      parse_response = HTTParty.get "http://api.adioso.com/v2/search/parse?q=#{URI.encode(options[:from])}+to+#{URI.encode(options[:to])}", auth_options
      fare_request = parse_response["search_url"].gsub /(end=)(\d*)([^\d]*)(\d*)/, "\\1#{date_to_unix_epoch(options[:end_date])}\\3#{date_to_unix_epoch(options[:start_date])}"
      fare = HTTParty.get fare_request, auth_options

			if fare["warnings"]
				create_event :payload => fare["warnings"]
			else
				event = fare["results"].min {|a,b| a["cost"] <=> b["cost"]}
				event["date"]  = Time.at(event["date"]).to_date.httpdate[0..15]
				event["route"] = "#{options[:from]} to #{options[:to]}" 
				create_event :payload => event
			end
    end
  end
end

app/models/agents/digest_email_agent.rb
module Agents
  class DigestEmailAgent < Agent
    MAIN_KEYS = %w[title message text main value].map(&:to_sym)
    default_schedule "5am"

    description <<-MD
      The DigestEmailAgent collects any Events sent to it and sends them all via email when run.
      The email will be sent to your account's address and will have a `subject` and an optional `headline` before
      listing the Events.  If the Events' payloads contain a `:message`, that will be highlighted, otherwise everything in
      their payloads will be shown.

      Set `expected_receive_period_in_days` to the maximum amount of time that you'd expect to pass between Events being received by this Agent.
    MD

    def default_options
      {
          :subject => "You have some notifications!",
          :headline => "Your notifications:",
          :expected_receive_period_in_days => "2"
      }
    end

    def working?
      last_receive_at && last_receive_at > options[:expected_receive_period_in_days].to_i.days.ago
    end

    def validate_options
      errors.add(:base, "subject and expected_receive_period_in_days are required") unless options[:subject].present? && options[:expected_receive_period_in_days].present?
    end

    def receive(incoming_events)
      incoming_events.each do |event|
        self.memory[:queue] ||= []
        self.memory[:queue] << event.payload
      end
    end

    def check
      if self.memory[:queue] && self.memory[:queue].length > 0
        lines = self.memory[:queue].map {|item| present(item) }
        puts "Sending mail to #{user.email}..." unless Rails.env.test?
        SystemMailer.delay.send_message(:to => user.email, :subject => options[:subject], :headline => options[:headline], :lines => lines)
        self.memory[:queue] = []
      end
    end

    def present(item)
      if item.is_a?(Hash)
        MAIN_KEYS.each do |key|
          if item.has_key?(key)
            return "#{item[key]}" + ((item.length > 1 && item.length < 5) ? " (#{present_hash item, key})" : "")
          elsif item.has_key?(key.to_s)
            return "#{item[key.to_s]}" + ((item.length > 1 && item.length < 5) ? " (#{present_hash item, key.to_s})" : "")
          end
        end
        present_hash item
      else
        item.to_s
      end
    end

    def present_hash(hash, skip_key = nil)
      hash.to_a.sort_by {|a| a.first.to_s }.map { |k, v| "#{k}: #{v}" unless [skip_key].include?(k) }.compact.to_sentence
    end
  end
end

app/models/agents/post_agent.rb
module Agents
    class PostAgent < Agent
        cannot_be_scheduled!

        description <<-MD
            Post Agent receives events from other agents and send those events as the contents of a post request to a specified url. `post_url` field must specify where you would like to receive post requests and do not forget to include URI scheme(`http` or `https`)
        MD

        event_description <<-MD
            Does not produce any event.
        MD

        def default_options
            {
                :post_url => "http://www.example.com",
                :expected_receive_period_in_days => 1
            }
        end

        def working?
            last_receive_at && last_receive_at > options[:expected_receive_period_in_days].to_i.days.ago
        end

        def validate_options
            unless options[:post_url].present? && options[:expected_receive_period_in_days].present? 
                errors.add(:base, "post_url and expected_receive_period_in_days are required fields")
            end
        end

        def post_event(uri,event)
            req = Net::HTTP::Post.new(uri.request_uri)
            req.form_data = event
            Net::HTTP.start(uri.hostname, uri.port, :use_ssl => uri.scheme == "https") { |http| http.request(req) }
        end

        def receive(incoming_events)
            incoming_events.each do |event|
                uri = URI options[:post_url]
                post_event uri, event.payload
            end
        end
    end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
    @agents = current_user.agents.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @agents }
    end
  end

  def run
    Agent.async_check(current_user.agents.find(params[:id]).id)
    redirect_to agents_path, notice: "Agent run queued"
  end

  def type_details
    agent = Agent.build_for_type(params[:type], current_user, {})
    render :json => {
        :can_be_scheduled => agent.can_be_scheduled?,
        :can_receive_events => agent.can_receive_events?,
        :options => agent.default_options,
        :description_html => agent.html_description
    }
  end

  def event_descriptions
    html = current_user.agents.find(params[:ids].split(",")).group_by(&:type).map { |type, agents|
      agents.map(&:html_event_description).uniq.map { |desc|
        "<p><strong>#{type}</strong><br />" + desc + "</p>"
      }
    }.flatten.join()
    render :json => { :description_html => html }
  end

  def remove_events
    @agent = current_user.agents.find(params[:id])
    @agent.events.delete_all
    redirect_to agents_path, notice: "All events removed"
  end

  def propagate
    details = Agent.receive!
    redirect_to agents_path, notice: "Queued propagation calls for #{details[:event_count]} event(s) on #{details[:agent_count]} agent(s)"
  end

  def show
    @agent = current_user.agents.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @agent }
    end
  end

  def new
    @agent = current_user.agents.build

    respond_to do |format|
      format.html
      format.json { render json: @agent }
    end
  end

  def edit
    @agent = current_user.agents.find(params[:id])
  end

  def diagram
    @agents = current_user.agents.includes(:receivers)
  end

  def create
    @agent = Agent.build_for_type(params[:agent].delete(:type),
                                  current_user,
                                  params[:agent])
    respond_to do |format|
      if @agent.save
        format.html { redirect_to agents_path, notice: 'Your Agent was successfully created.' }
        format.json { render json: @agent, status: :created, location: @agent }
      else
        format.html { render action: "new" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @agent = current_user.agents.find(params[:id])

    respond_to do |format|
      if @agent.update_attributes(params[:agent])
        format.html { redirect_to agents_path, notice: 'Your Agent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @agent = current_user.agents.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/agent_helper.rb
module AgentHelper
  def agent_show_view(agent)
    name = agent.short_type.underscore
    if File.exists?(Rails.root.join("app", "views", "agents", "agent_views", name, "_show.html.erb"))
      File.join("agents", "agent_views", name, "show")
    end
  end

  def agent_show_class(agent)
    agent.short_type.underscore.dasherize
  end
end

app/views/agents/_form.html.erb
<%= form_for(@agent,
             :as => :agent,
             :url => @agent.new_record? ? agents_path : agent_path(@agent),
             :method => @agent.new_record? ? "POST" : "PUT") do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this Agent from being saved:</h2>
      <ul>
      <% @agent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='pull-right well description span6'>
    <%= @agent.html_description unless @agent.new_record? %>
  </div>

  <div class='pull-right well event-descriptions span6 hidden'>
  </div>

  <% if @agent.new_record? %>
    <div class="control-group type-select">
      <%= image_tag "spinner-arrows.gif", :class => "spinner" %>
      <%= f.label :type, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :type, options_for_select(Agent.types.map {|type| [type.to_s.gsub(/^.*::/, ''), type.to_s] }, @agent.type), :class => 'span4' %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'span4' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :schedule, :class => 'control-label' %>
    <div class="controls schedule-region" data-can-be-scheduled="<%= @agent.can_be_scheduled? %>">
      <%= f.select :schedule, options_for_select(Agent::SCHEDULES.map {|s| [s.humanize.titleize, s] }, @agent.schedule), :class => 'span4' %>
      <span class='cannot-be-scheduled text-info'>This type of Agent cannot be scheduled.</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :sources, :class => 'control-label' %>
    <div class="controls link-region" data-can-receive-events="<%= @agent.can_receive_events? %>">
      <%= f.select(:source_ids,
                   options_for_select((current_user.agents - [@agent]).map {|s| [s.name, s.id] },
                                      @agent.source_ids),
                   {}, { :multiple => true, :size => 5, :class => 'span4 multi-select' }) %>
      <span class='cannot-receive-events text-info'>This type of Agent cannot receive events.</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :options, :class => 'control-label' %>
    <div class="controls">
      <textarea rows="10" id="agent_options" name="agent[options]" class="span8 live-json-editor">
        <%= ((@agent.new_record? && @agent.options == {}) ? @agent.default_options : @agent.options).to_json %>
      </textarea>
    </div>
  </div>

  <div class='form-actions' style='clear: both'>
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/agents/diagram.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Agent Event Flow</h2>
      </div>
      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
      </div>

      <div class='digraph'>
        <%
           dot_format_string = "digraph foo {"
           @agents.each.with_index do |agent, index|
             dot_format_string += "\"#{agent.name}\";"
             agent.receivers.each do |receiver|
               dot_format_string += "\"#{agent.name}\"->\"#{receiver.name}\";"
             end
           end
           dot_format_string = dot_format_string + "}"
        %>

        <img src="https://chart.googleapis.com/chart?cht=gv&chl=<%= CGI::escape dot_format_string %>" />
      </div>
    </div>
  </div>
</div>

app/views/agents/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Editing your <%= @agent.short_type %></h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
        <%= link_to '<i class="icon-asterisk"></i> Show'.html_safe, agent_path(@agent), class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/agents/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Your Agents</h2>
      </div>

      <table class='table table-striped'>
        <tr>
          <th>Name</th>
          <th>Last Check</th>
          <th>Last Event Out</th>
          <th>Last Event In</th>
          <th>Events</th>
          <th>Schedule</th>
          <th>Working?</th>
          <th></th>
        </tr>

        <% @agents.each do |agent| %>
            <tr>
              <td>
                <%= agent.name %>
                <br/>
                <span class='muted'><%= agent.short_type.titleize %></span>
              </td>
              <td>
                <% if agent.cannot_be_scheduled? %>
                    N/A
                <% else %>
                    <%= agent.last_check_at ? time_ago_in_words(agent.last_check_at) + " ago" : "never" %>
                <% end %>
              </td>
              <td><%= agent.last_event_at ? time_ago_in_words(agent.last_event_at) + " ago" : "never" %></td>
              <td>
                <% if agent.cannot_receive_events? %>
                    N/A
                <% else %>
                    <%= agent.last_receive_at ? time_ago_in_words(agent.last_receive_at) + " ago" : "never" %>
                <% end %>
              </td>
              <td><%= link_to(agent.events_count || 0, events_path(:agent => agent.to_param)) %></td>
              <td><%= (agent.schedule || "n/a").to_s.humanize.titleize %></td>
              <td><%= working(agent) %></td>
              <td>
                <div class="btn-group">
                  <%= link_to 'Show', agent_path(agent), class: "btn btn-mini" %>
                  <%= link_to 'Edit', edit_agent_path(agent), class: "btn btn-mini" %>
                  <%= link_to 'Delete', agent_path(agent), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-mini" %>
                  <% if agent.can_be_scheduled? %>
                      <%= link_to 'Run', run_agent_path(agent), method: :post, class: "btn btn-mini" %>
                  <% else %>
                      <%= link_to 'Run', "#", class: "btn btn-mini disabled" %>
                  <% end %>
                </div>
              </td>
            </tr>
        <% end %>
      </table>

      <%= paginate @agents, :theme => 'twitter-bootstrap' %>

      <br/>

      <div class="btn-group">
        <%= link_to '<i class="icon-plus"></i> New Agent'.html_safe, new_agent_path, class: "btn" %>
        <%= link_to '<i class="icon-refresh"></i> Run event propagation'.html_safe, propagate_agents_path, method: 'post', class: "btn" %>
        <%= link_to '<i class="icon-random"></i> View diagram'.html_safe, diagram_agents_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/agents/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Create a new Agent</h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/agents/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>

      <div class="tabbable tabs-left">
        <ul class="nav nav-tabs" id="show-tabs">
          <% if agent_show_view(@agent).present? %>
            <li class='active'><a href="#summary" data-toggle="tab"><i class='icon-picture'></i> Summary</a></li>
            <li><a href="#details" data-toggle="tab"><i class='icon-indent-left'></i> Details</a></li>
          <% else %>
            <li class='disabled'><a><i class='icon-picture'></i> Summary</a></li>
            <li class='active'><a href="#details" data-toggle="tab"><i class='icon-indent-left'></i> Details</a></li>
          <% end %>

          <% if @agent.events.count > 0 %>
            <li><%= link_to '<i class="icon-random"></i> Events'.html_safe, events_path(:agent => @agent.to_param) %></li>
          <% end %>
          <li><%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path %></li>
          <li><%= link_to '<i class="icon-pencil"></i> Edit'.html_safe, edit_agent_path(@agent) %></li>

          <% if @agent.events.count > 0 %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Actions <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li>
                    <%= link_to '<i class="icon-trash"></i> Delete all events'.html_safe, remove_events_agent_path(@agent), method: :delete, data: {confirm: 'Are you sure you want to delete ALL events for this Agent?'}, :tabindex => "-1" %>
                  </li>
              </ul>
            </li>
          <% end %>

        </ul>

        <div class="tab-content">
          <div class="tab-pane <%= agent_show_view(@agent).present? ? "active" : "disabled" %>" id="summary">
            <h2><%= @agent.name %> Summary</h2>

            <% if agent_show_view(@agent).present? %>
              <div class="show-view <%= agent_show_class(@agent) %>">
                <%= render agent_show_view(@agent) %>
              </div>
            <% end %>
          </div>

          <div class="tab-pane <%= agent_show_view(@agent).present? ? "" : "active" %>" id="details">
            <h2><%= @agent.name %> Details</h2>

            <p>
              <b>Type:</b>
              <%= @agent.short_type.titleize %>
            </p>

            <p>
              <b>Schedule:</b>
              <%= (@agent.schedule || "n/a").humanize.titleize %>
            </p>

            <p>
              <b>Last checked:</b>
              <% if @agent.cannot_be_scheduled? %>
                N/A
              <% else %>
                <%= @agent.last_check_at ? time_ago_in_words(@agent.last_check_at) + " ago" : "never" %>
              <% end %>
            </p>

            <p>
              <b>Last event created:</b>
              <%= @agent.last_event_at ? time_ago_in_words(@agent.last_event_at) + " ago" : "never" %>
            </p>

            <p>
              <b>Last received event:</b>
              <% if @agent.cannot_receive_events? %>
                N/A
              <% else %>
                <%= @agent.last_receive_at ? time_ago_in_words(@agent.last_receive_at) + " ago" : "never" %>
              <% end %>
            </p>

            <p>
              <b>Event count:</b>
              <%= link_to @agent.events.count, events_path(:agent => @agent.to_param) %>
            </p>

            <p>
              <b>Working:</b>
              <%= working @agent %>
            </p>

            <p>
              <b>Options:</b>
              <pre><%= PP.pp(@agent.options, "") %></pre>
            </p>

            <p>
              <b>Memory:</b>
              <pre><%= PP.pp(@agent.memory, "") %></pre>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>